#!/bin/bash

#### Wifi Setup (WPA Supplicant)
##  Replaces the magic of https://github.com/RPi-Distro/raspberrypi-net-mods/blob/master/debian/raspberrypi-net-mods.service
##  See: https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md


#echo -e "\e[30;48;5;11m=============== SET Wi-Fi ======= \e[31;48;5;11mSTART\e[30;48;5;11m =\e[0m"


# Set Wifi settings
cat > /etc/wpa_supplicant/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US
network={
    ssid="WiFi_Name"
    psk="WiFi_Password"
}
EOF
chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf
wpa_cli -i wlan0 reconfigure

sleep 5


#echo -e "\e[30;48;5;11m=============== SET Wi-Fi ========= \e[32;48;5;11mEND\e[30;48;5;11m =\e[0m"
